// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// The Prisma CLI (unlike Next.js) does not auto-load .env.local. Load it first,
// then fall back to .env, so migrate/generate see DATABASE_URL(_UNPOOLED).
loadEnv({ path: ".env.local" });
loadEnv();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a DIRECT (unpooled) connection. Neon's pooled endpoint
    // (PgBouncer, transaction mode) can't hold the session advisory lock that
    // `prisma migrate deploy` requires, which causes the pg_advisory_lock
    // timeout during the Vercel build. Fall back to the pooled URL for local.
    url:
      process.env["DATABASE_URL_UNPOOLED"] ??
      process.env["DIRECT_DATABASE_URL"] ??
      process.env["DATABASE_URL"],
  },
});
